repo_url: https://raw.githubusercontent.com/Xpos587/fdroid/main/fdroid/repo
repo_name: Xpos587 Apps Repository
repo_description: >
  Curated collection of high-quality Android applications.
  Features official binaries from trusted developers,
  including privacy tools, communication apps,
  open-source alternatives, and useful utilities.
  Covers both FOSS and proprietary applications for enhanced mobile experience.

keystore: keystore.p12
repo_keyalias: $REPO_KEYALIAS
keystorepass: $KEYSTOREPASS
keypass: $KEYSTOREPASS
archive_older: 0
