name: Generate F-Droid repo

on:
  repository_dispatch:
    types: [fdroid-update]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  apps:
    name: "Generate repo from apps listing"
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create basic directory structure
        run: mkdir -p fdroid/repo

      - name: Restore correct mtime
        run: |
          sudo apt install git-restore-mtime 
          git restore-mtime

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-fdroid
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install F-Droid server software
        run: |
          sudo add-apt-repository ppa:fdroid/fdroidserver
          sudo apt-get update
          sudo apt install apksigner

      - name: Install fdroidserver
        run: |
          pip install git+https://gitlab.com/fdroid/fdroidserver.git
          fdroid --version

      - name: Set up repo secrets
        run: |
          echo "${{ secrets.FDROID_KEYSTORE_P12 }}" | base64 -d - > fdroid/keystore.p12
          echo "${{ secrets.FDROID_CONFIG_YML }}" | base64 -d - > fdroid/config.yml
          chmod 600 fdroid/keystore.p12 fdroid/config.yml
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - uses: actions/setup-go@v4
        name: Set up Go
        with:
          go-version: "^1.23.0"
          cache-dependency-path: metascoop/go.sum

      - name: Run update script
        run: bash update.sh 2>&1
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
